# Generated by Django 5.1.5 on 2025-02-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
